### ISSUE TITLE
export to HTML dies when source blocks with named "c" language exist

### ISSUE THREAD

**Issue by ewa** [fniessen/orgmk#9]
Using orgmk revision 42ceb56, trying to run my test doc through org2html dies as follows.  I don't know what causes it (and I could swear that it worked earlier with the same revision), but it seems to be an issue with any cc-derived mode.

Here's the code:
````org
#+TITLE: Test Doc
#+AUTHOR: Eric Anderson


#+BEGIN_SRC c
 int main(void){}
#+END_SRC
````

And here's the output:
`org2html test_doc_0.org 2>&1 | tee log.txt`

````
This is org2html, version: 20150710.1537.
Launching /usr/bin/emacs...
Emacs 24.3.1 (gnu/linux)
Loading /usr1/home/andersoe/src/orgmk-orig/site-lisp/orgmk.el...
Current value of `shell-file-name': /bin/bash
... changed to: bash
Org mode version 8.2.6 (org @ /usr1/home/andersoe/.emacs.d/elpa/org-20140505/)
LaTeX command: ("pdflatex -interaction=nonstopmode -output-directory=%o %f" "pdflatex -interaction=nonstopmode -output-directory=%o %f" "pdflatex -interaction=nonstopmode -output-directory=%o %f")
Loading /usr1/home/andersoe/src/orgmk-orig/lisp/org-latex-classes.el (source)...
Loading vc-git...
Convergence after 1 iterations
Saving file /usr1/home/andersoe/src/orgmk/test/test_doc_0.orgmk...
Wrote /usr1/home/andersoe/src/orgmk/test/test_doc_0.orgmk
Loading cc-langs...
Symbol's function definition is void: nil
org2html: Exported file wasn't produced
````

[log.txt](https://github.com/fniessen/orgmk/files/107380/log.txt)
[test_doc_0.org](https://github.com/fniessen/orgmk/files/107381/test_doc_0.org.txt)

**Comment by fniessen** [comment]
Hello Eric. I remember something about this as well. This really has to do with the language c itself. It's a bug/feature in Emacs modes.

I couldn't find the information where I'd put it, but you should be able to confirm that quite easily by searching in the newsgroups, or asking. Once the problem is fully framed, the solution will be as easy as adding some libraries to load -- or something of this kind.
